version: '3.9'
services:
  mongodb:
    image: mongo:8.0.5
    container_name: mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - mongo-data:/data/db/mongo
    ports:
      - 27017:27017
    networks:
      - investment-network

  mongo-express:
    image: mongo-express
    ports:
      - "18081:8081"
    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=passcode
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
    networks:
      - investment-network
  
  zipkin-server:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 512m
    expose:
      - "9411"
    ports:
      - "9411:9411"
    networks:
      - investment-network
  
  discovery-service:
    image: dockertmt/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - investment-network

  portfolio-service:
    image: dockertmt/portfolio-service:0.0.1
    ports:
      - "8082:8082"
    networks:
      - investment-network
    depends_on:
      discovery-service:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
     
volumes:
  mongo-data:
  
networks:
  investment-network:
